### ISSUE TITLE
Matrix type not public?

### ISSUE THREAD

**Issue by holtgrewe** [anergictcell/hpo#38]
Maybe I'm missing something but it seems that the Matrix type must be `pub`. Otherwise, users of the library cannot implement `SimilarityCombiner`.

**Comment by anergictcell** [comment]
Hi, yes, that is true actually. I initially did not want to make this a public type, because I'm not so happy with the current implementation. 
But if that prevents custom implementations it defeats the purpose, so I'll make it public as well. Let me brush up on the documentation beforehand though.
Also here, feel free to crate a PR if this is something you need and can contribute to. I'm not sure when I'll get the time to do it myself.
