### ISSUE TITLE
Derive Clone for Ontology

### ISSUE THREAD

**Issue by holtgrewe** [anergictcell/hpo#45]
This would be useful in tests in the case where copies are needed.

For example, when putting an `Ontology` into an Actix server, a copy is needed. I could load the ontology once into a `OnceCell` and then copy for each tests. This is not possible right now.

**Comment by holtgrewe** [comment]
@anergictcell thanks. Could you make a crates.io release of a version including this patch?

**Comment by anergictcell** [comment]
@holtgrewe : I'm currently traveling without my laptop. I will make a release once I'm back home end of June. I guess I should also add crates.io releases to the GitHub actions so I can release remotely as well.

**Comment by anergictcell** [comment]
@holtgrewe : I made a new release now that include your fixes: https://crates.io/crates/hpo/0.8.1

But you can also use `OnceCell` without `Clone`. I do this in [hpo3](https://github.com/anergictcell/hpo3) to have a global Ontology (e.g. here: https://github.com/anergictcell/hpo3/blob/main/src/lib.rs#L38).

What are your use-cases to have to clone the Ontology? Just trying to understand if I overlooked some needed functionality. I tried to design `Ontology` so that it can be used completely as reference for pretty much all functionality. The underlying data structure is rather big and not very memory efficient, so cloning it repeatedly could cause some performance issues.

**Comment by holtgrewe** [comment]
Thanks for your reply and the release. I'll have a look at `hpo3`.
